## Tensorflow Denemeleri

Geçtiğimiz haftanın büyük bir bölümünde, Derin Öğrenme modellerinizde tensörler kullandınız. Bugünkü zorluklar boyunca, tensörleri kapsamlı bir şekilde kullanacak ve bazı alışılmadık model mimarileriyle çalışacaksınız. 


Bu ısınma çalışmasında, bazı yeni yöntemlerle tanışacaksınız. 

Buradaki tüm yöntemler, günün ilerleyen saatlerinde karşılaşacağınız zorlukları 100 kat daha kolay hale getirecek, bu nedenle daha sonra takılırsanız, doğru cevapları nasıl bulduğunuzu görmek için buraya geri dönün. 

In [1]:
import tensorflow as tf

In [2]:

import numpy as np

A) `tf.ones` kullanarak (3,3) şeklinde birler ile doldurulmuş bir tensör `a` oluşturun.

In [3]:
# (3, 3) boyutunda, içi 1 dolu tensör
a = tf.ones((3, 3))
print(a)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


B) tf.expand_dims kullanarak `a`'yı `b` adlı (1,3,3) şekilli bir nesne haline getirin.

In [4]:
# a tensörünün başına (0. indeks) yeni bir boyut ekliyoruz
b = tf.expand_dims(a, axis=0)
print(b.shape)

(1, 3, 3)


C) Boyutu (9,1) olan ve sıfırlarla dolu bir tensör `c` oluşturun.

In [5]:
# (9, 1) boyutunda, içi 0 dolu tensör
c = tf.zeros((9, 1))
print(c)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(9, 1), dtype=float32)


D) `c`'yi (1, 3, 3) şeklinde yeniden şekillendirin. Adını `d` olarak belirleyin.

In [6]:
# c tensörünü al, (1, 3, 3) şekline sok
d = tf.reshape(c, (1, 3, 3))
print("Eski şekil:", c.shape)
print("Yeni şekil:", d.shape)

Eski şekil: (9, 1)
Yeni şekil: (1, 3, 3)


E) `tf.matmul` kullanarak `b` ve `d` matrislerini birbiriyle çarpın ve şimdi tensörü `e`'ye atayın. 

In [7]:
# b ve d matrislerini çarp
e = tf.matmul(b, d)
print(e)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 3, 3), dtype=float32)


F) Aşağıda bir `numpy` dizisi bulunmaktadır. Bunu `array_tensor` adlı bir tensöre dönüştürün. Ardından `tf.cast` kullanarak bunun `int` değil `float` türü olduğundan emin olun. Sonucu `f`'ye atayın.

In [8]:
import numpy as np

In [9]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [10]:
# 1. Önce NumPy dizisini Tensor'a çevirelim
array_tensor = tf.convert_to_tensor(array)

# 2. Veri tipini integer'dan float'a (ondalıklı) çevirelim
f = tf.cast(array_tensor, dtype=tf.float32)

print("Veri Tipi:", f.dtype)
print("Şekil:", f.shape)

Veri Tipi: <dtype: 'float32'>
Şekil: (1, 4, 3)


G) `f`'nin __last column__ değerleri seçin ve bunu `g`'ye kaydedin. Açıkça belirtmek gerekirse, `g`'nin şekli (4,) olmalı ve `3,3,6,9` değerlerini içermelidir. 

In [11]:
# Tensörün içinden [ilk paket, tüm satırlar, son sütun] verisini çek
g = f[0, :, -1]

print("Sonuç:", g)
print("Beklenen Şekil (4,) mi?:", g.shape)

Sonuç: tf.Tensor([3. 3. 6. 9.], shape=(4,), dtype=float32)
Beklenen Şekil (4,) mi?: (4,)


H) g boyutlarını (4,1) şekline gelecek şekilde genişletin. Bunu `h`'ye atayın.

In [12]:
# g vektörünü (4, 1) boyutuna getiriyoruz
h = tf.expand_dims(g, axis=-1)

print("Eski Şekil:", g.shape)
print("Yeni Şekil:", h.shape)

Eski Şekil: (4,)
Yeni Şekil: (4, 1)


I) İsteğe bağlı `transpose_b` argümanıyla `tf.matmul` kullanarak e ile f'yi çarpın (konumsal argümanlarınızda önce `e`, sonra `f` gelmelidir). Bunu `i`'ye atayın.

In [13]:
# e ile f'yi çarpacağız ama f'nin transpozunu alarak (transpose_b=True)
i = tf.matmul(e, f, transpose_b=True)

print("Sonuç Şekli:", i.shape)
print(i)

Sonuç Şekli: (1, 3, 4)
tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 3, 4), dtype=float32)


J) Birlerle dolu bir `(10,10)` tensör oluşturun. Ardından `tf.linalg.band_part()` kullanarak matrisin üst üçgenini maskeleme yapın (yani üst üçgenin tamamı 0 olmalıdır). `j`'ye atayın.

In [14]:
# 1. Önce 10x10'luk, içi 1 dolu bir matris yapalım
ones_matrix = tf.ones((10, 10))

# 2. Alt tarafı tut (-1), üst tarafı sil (0)
# Bu işlem üst üçgeni 0 yapar.
j = tf.linalg.band_part(ones_matrix, num_lower=-1, num_upper=0)

print(j)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


K) Aşağıdaki `number_list`'i alın ve bir tensör haline getirin. Bunu `k`'ye atayın.

In [15]:
number_list = [1,2,3,4,8]

In [16]:
# Listeyi tensöre çevir
k = tf.convert_to_tensor(number_list)

print(k)

tf.Tensor([1 2 3 4 8], shape=(5,), dtype=int32)


L) `tf.expand_dims` kullanarak `k`'yi (1,5) şekilli bir tensör haline getirin. `l`'ye atayın.

In [17]:
# k tensörüne "satır" boyutu ekliyoruz (en başa)
l = tf.expand_dims(k, axis=0)

print("k'nın şekli:", k.shape)
print("l'nin şekli:", l.shape)

k'nın şekli: (5,)
l'nin şekli: (1, 5)


M) `tf.tile` kullanarak `l` (okunuşu “L”) 50 kez tekrarlayın, sonuçta `(50, 5)` şeklinde olsun. `m`'ye atayın.

In [18]:
# [50 kere aşağı, 1 kere yana] kopyala
m = tf.tile(l, multiples=[50, 1])

print("m'nin şekli:", m.shape)
print(m)

m'nin şekli: (50, 5)
tf.Tensor(
[[1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]], shape=(50, 5), dtype=int32)


N) Basit bir Boolean ifadesi kullanarak, `m`'nin 3 olduğu yerler için `True` değerleri ve 3 olmadığı yerler için `False` değerleri içeren bir tensör oluşturun. `n`'ye atayın.

In [19]:
# m tensöründe 3'e eşit olan yerler True olsun
n = (m == 3)

print(n)
# Çıktıda True ve False'lar göreceksin

tf.Tensor(
[[False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]

O) Değişkeniniz `m` içindeki her değeri 3'e bölün. `o`'ya atayın.

In [20]:
# Tüm elemanları 3'e böl
o = m / 3

print(o)

tf.Tensor(
[[0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0

P) `tf.concat()` kullanarak, aşağıdaki (5,5) ve (5,5) şekilli iki tensörün listesini alın ve bunları (10,5) şekilli son bir tensöre dönüştürün. `p`'ye atayın. Birleştirme eksenini dikkatlice düşünün.

In [21]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]

In [22]:
# tensor_list zaten tanımlıydı, onu kullanıyoruz
# axis=0 diyerek alt alta yapıştırıyoruz
p = tf.concat(tensor_list, axis=0)

print("Sonuç Şekli:", p.shape)

Sonuç Şekli: (10, 5)


### Cevaplarını Kontrol Et

In [23]:
from nbresult import ChallengeResult

result = ChallengeResult(
    "tensors",
    a=a.numpy(),
    b=b.numpy(),
    c=c.numpy(),
    d_shape=tuple(d.shape),
    e=e.numpy(),
    f=f.numpy(),
    g=g.numpy(),
    h=h.numpy(),
    i=i.numpy(),
    j=j.numpy(),
    k=k.numpy(),
    l=l.numpy(),
    m=m.numpy(),
    n=n.numpy(),
    o=o.numpy(),
    p_shape=tuple(p.shape),
)

result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/berkayturhan/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/berkayturhan/S19D2-S-Data-tensor-trials/tests
plugins: dash-3.3.0, anyio-4.8.0, langsmith-0.5.0, typeguard-4.4.2
collecting ... collected 15 items

test_tensors.py::TestTensors::test_a PASSED                              [  6%]
test_tensors.py::TestTensors::test_b PASSED                              [ 13%]
test_tensors.py::TestTensors::test_c PASSED                              [ 20%]
test_tensors.py::TestTensors::test_d_shape PASSED                        [ 26%]
test_tensors.py::TestTensors::test_e PASSED                              [ 33%]
test_tensors.py::TestTensors::test_f PASSED                              [ 40%]
test_tensors.py::TestTensors::test_g PASSED                              [ 46%]
test_tensors.py::TestTensors::test_i PASSED     

### Harika iş 🔥

Şimdi modellemeye başlama zamanı!